name: publish
on:
  push:
    tags:
    - 'release-*'
jobs:
  publish:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}